### ISSUE TITLE
[Alert component] - new component

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#1029]
EDIT: PR is here: https://github.com/livechat/my.livechatinc.com/pull/20608

The current task depends on https://github.com/livechat/design-system/issues/1030

Prepare new component based on design spec
https://www.figma.com/file/9FDwjR8lYvincseDkKypC4/Component-Documentations?type=design&node-id=17663-19037&mode=design&t=WHPU2435oBmvlTwF-4

**Comment by VadymBezpalko** [comment]
The task is moved to the AA repo: https://github.com/livechat/my.livechatinc.com/pull/20608
