### ISSUE TITLE
[Colors] - Add New & updates

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#1034]
We need to have new group of color tokens with opacity

**SurfaceOpacity**
- Basic
- Invert

- [ ] Tokens for SurfaceOpacity**Basic**
Rename token:
 `--surface-primary-hover-opacity ` - to new name - `--surface-opacity-basic-hover` Light `rgba(19, 19, 23, 0.07)` | Dark `rgba(255, 255, 255, 0.08)`
Add new token:
`--surface-opacity-basic-active`Light `rgba(19, 19, 23, 0.09)` | Dark `rgba(255, 255, 255, 0.12)`

- [ ] Tokens for SurfaceOpacity**Invert**
**Add new tokens:**
`--surface-opacity-invert-hover` Light `rgba(255, 255, 255, 0.1)` | Dark `rgba(255, 255, 255, 0.1)`
`--surface-opacity-invert-active` Light `rgba(255, 255, 255, 0.15)` | Dark `rgba(255, 255, 255, 0.12)`

**Comment by VadymBezpalko** [comment]
I will not rename the `surface-primary-hover-opacity ` to not cause the conflicts, I'll mark it as deprecated instead and will create a new entry with new values.
