### ISSUE TITLE
[BUG][Picker] Nested buttons produce invalid HTML

### ISSUE THREAD

**Issue by lwojciechowski** [livechat/design-system#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The picker contains a `<button>` element nested in another `<button>`. That's not correct HTML, and it produces errors in the console.

<img width="1123" alt="image" src="https://github.com/livechat/design-system/assets/605219/d3c87149-a95e-40ac-811f-8903493b691e">

![image](https://github.com/livechat/design-system/assets/605219/d68f558c-557d-4376-ab84-d97dcb1ddcd6)

### Steps To Reproduce

1. Use `Picker` with multi-select.
2. Pick any option.

### Expected Behavior

The console is clear of errors and component produces valid HTML.

### Design system package(s) version

examples:
  - @livechat/design-system-react-components@1.19.1

**Comment by RakowskiPrzemyslaw** [comment]
I also encountered this bug, how's progress on this one?
