### ISSUE TITLE
[PromoBannerv2] Allow to pass icon and iconPosition properties to component's buttons

### ISSUE THREAD

**Issue by quarties** [livechat/design-system#1081]
### Description

Currently, only 3 following Button component properties are available to pass in the PromoBannerV2 component:
```tsx
  /**
   * Shows the primary CTA button
   */
  primaryButton?: {
    handleClick: () => void;
    label: string;
    kind?: ButtonKind;
  };
```

We additionally need to pass the `icon` and `iconPosition` properties. Also, it would be nice to have all possible properties supported here out of the box.

### Design

<img width="924" alt="image" src="https://github.com/livechat/design-system/assets/29309941/5664a909-191c-4eea-8b2e-9f2e2e46b5d2">

**Comment by vladko-uxds** [comment]
Duplicates by
https://github.com/livechat/design-system/issues/873
