### ISSUE TITLE
[BUG] Tag component with outlined gradient

### ISSUE THREAD

**Issue by MrVorgoth** [livechat/design-system#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="499" alt="Screenshot 2024-06-03 at 08 30 06" src="https://github.com/livechat/design-system/assets/20707838/3a6f3a33-a231-408e-b1ce-e6867596e549">

As seen on image above (it's from story book) the issue I see is that outline prop is not working alongisde gradient option in `Tag` component

### Steps To Reproduce

No steps however this should work:
```<Tag kind="gradient02" outline>``` // now outline is doing nothing

### Expected Behavior

Outline should actually outline the component

### Design system package(s) version

examples:
  - @livechat/design-system-react-components@1.22.4

### Environment

```markdown
macbook M1 Pro / macOS / Chrome 125.0.6422.112
```

**Comment by marcinsawicki** [comment]
It is not possible to apply a gradient as a border color or to SVG icons that are not prepared for this, so the `outline` version does not change anything in these cases and this is the intended layout.
