### ISSUE TITLE
[BUG] NumericInput: arrows overflow the input value

### ISSUE THREAD

**Issue by kubaczerwinski77** [livechat/design-system#1150]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Input arrows overflows the input value while resizing.

### Steps To Reproduce

1. Render `NumericInput` in the div.
2. Decrease div width.

### Expected Behavior

The input value should be visible to user

### Screenshots

![Image](https://github.com/livechat/design-system/assets/86623851/c15833ce-5022-461e-ab9e-6ed2eb68ba3c)

### Design system package(s) version

examples:
  - @livechat/design-system-react-components@1.19.4

### Environment

Device: Macbook Pro 2021
OS: macOS Sonoma 14.3.1
Browser: Chrome
Version: 125.0.6422.142

**Comment by VadymBezpalko** [comment]
Duplicates https://github.com/livechat/design-system/issues/1149
