### ISSUE TITLE
[Tag] - user can apply any token to content and surface

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#1211]
Update Tag component with option to apply any color token to Content and Surface
https://design.livechat.com/?path=/story/components-tag--kinds

**Comment by VadymBezpalko** [comment]
To achieve this we can use already existing `customColor` prop, but we need to modify the existing logic for text color discovering and switch from `getContrast` function, that cannot work with our CSS tokens, and replace it with native SCSS function called `lightness()`. Using scss function we will be able to pass CSS tokens so SCSS mechanism will retrieve proper value from our CSS constants.
