### ISSUE TITLE
[question] External contributors 

### ISSUE THREAD

**Issue by kamilmateusiak** [livechat/design-system#282]
Hello guys. I see that you are actively developing a new version of design system (v1). It looks really awesome! I would like to ask a quick question: do you have any issues or tasks (like components migration to new architecture) that an external contributor can help you with? Do you plan to add some issues ie. with "good first issue" label? Are you open to external collaboration at all?

**Comment by skrabkab-design** [comment]
Hey Kamil! We've prepared one issue that could be good for an external collaboration. [Here](https://github.com/livechat/design-system/issues/284) you can find more details.
