### ISSUE TITLE
Move Date picker to new repository [DS-165]

### ISSUE THREAD

**Issue by skrabkab-design** [livechat/design-system#284]
We're aiming to move [this](https://livechat.github.io/design-system/#/Components/DatePicker) component to Storybook

To do:
- Make sure to use appropriate typography tokens (see other components for reference – like Card or Radio button),
- Make sure to use color tokens - [Figma](https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=4478%3A40684)
- Make sure to use appropriate icons from the DS icon package,
- Introduce small visual tweaks [Figma](https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=4478%3A40684)
- Remove option to enter custom date manually in this type of date picker https://tppr.me/dww7X using inputs inside select looks pretty weird, we're also not using this pattern in AA, so looks like this exists only in DS,

**Comment by kamilmateusiak** [comment]
Hello. I am sorry for no info about work status for so long (I've had some personal stuff happening). Currently I have some free time and the component migration is almost done. Unfortunately I don't have access to the repository:
```
ERROR: Permission to livechat/design-system.git denied to kamilmateusiak.
fatal: Could not read from remote repository
```
If you didn't start the work on that yet and you are still interested in external contribution please add me as contributor to the repository.

**Comment by sgraczyk** [comment]
Canceled in favor of #331
