### ISSUE TITLE
[NumericInput] Click on controls results in wrong value

### ISSUE THREAD

**Issue by kamilmateusiak** [livechat/design-system#302]
Hello. I noticed that controls of NumericInput are not handled properly. When clicking multiple times something strange is happening with input state and the value is not correct. 

![numeric-input-issue](https://user-images.githubusercontent.com/24607370/158077897-2f497f89-7fac-4f32-8409-cefcb28be5d0.gif)

Steps to reproduce: 
- visit basic story of numeric input 
- click multiple (at least 3) times on up control of numeric input

**Comment by skrabkab-design** [comment]
Thanks for reporting @kamilmateusiak ! 🙌

@marcinsawicki Can you please take a look?

**Comment by marcinsawicki** [comment]
I can't reproduce this problem

**Comment by sgraczyk** [comment]
I'm also unable to reproduce. Closing.
