### ISSUE TITLE
[DatePicker] Component

### ISSUE THREAD

**Issue by MichalPaszowski** [livechat/design-system#331]
## Description
The DatePicker component under the hood uses the react-day-picker library. It has some LiveChat custom styles. You can check it out in official docs: http://react-day-picker.js.org.

Continuation of open contribution by Kamil Mateusiak [Move Date picker to a new repository [DS-165] · Issue #284 · livechat/design-system](https://github.com/livechat/design-system/issues/284)

## Design
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=4462%3A36608

[DS-165]: https://livechatinc.atlassian.net/browse/DS-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.21](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.21)
