### ISSUE TITLE
[Popover] should have z-index set to prevent content overlapping

### ISSUE THREAD

**Issue by MichalPaszowski** [livechat/design-system#332]
## Describe the bug
One image is worth a thousand words: 
![Image](https://user-images.githubusercontent.com/7773964/175543476-119fd3f4-e202-4da2-8639-ca38035bcc4c.png)

## Steps To Reproduce
Place popover near element with higher z-index.

## Expected behaviour
A popover should be over(hehe) other elements.

## Screenshots
![Image](https://user-images.githubusercontent.com/7773964/175543476-119fd3f4-e202-4da2-8639-ca38035bcc4c.png)

## Environment
N/A

## Additional context
N/A

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.22](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.22)
