### ISSUE TITLE
[Picker] Improvements (default selected option, search input disabling, z-index , and border-box)

### ISSUE THREAD

**Issue by marcinsawicki** [livechat/design-system#337]
## Description
Add missing functionality:
- possibility to provide default selected option
- possibility to disable search input

UI improvements:
- add `z-index` prop for the list to display on top of other items
- add `border-box` to prevent inheriting it from the parent, which allows to display the component as designed

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.16](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.16)
