### ISSUE TITLE
[Picker][Modal] Component falls behind footer due to issues with z-index

### ISSUE THREAD

**Issue by sgraczyk** [livechat/design-system#348]
## Describe the bug
I the `Picker` is used within `Modal` it is not showing correctly the list of items. It gets covered by a footer.

## Steps to reproduce
1. Have a `Picker` component in `Modal`'s body. Make sure it has several items.
2. Click on `Picker` to observe that it gets covered by the footer.

## Expected behavior
Either the `Design System` should introduce stacking levels, which would always keep dropdowns above, or the component should have a possibility to control the `z-index`.

## Screenshots
![image](https://user-images.githubusercontent.com/8076673/179942226-8d8aef8c-1e2a-44d8-97b1-86b5caae5976.png)

## Environment
 - Design system package(s) version: `@livechat/design-system-react-components@1.0.0-beta.16`

**Comment by marcinsawicki** [comment]
Already solved
