### ISSUE TITLE
[Picker] Event for reaching bottom of items list

### ISSUE THREAD

**Issue by sgraczyk** [livechat/design-system#349]
## Description
The component could handle a situation when it's used for paginated data. Reaching its bottom through scrolling could trigger an event that should be used to fetch the next page. There should also be a `threshold` prop that would allow configuring the moment when the event is triggered.

```ts
onBottomReached(): void;
bottomReachThreshold: number;
```

## Design
n/a

**Comment by VadymBezpalko** [comment]
These and even [more events and callbacks](https://virtuoso.dev/virtuoso-api-reference/) will be available through `virtuosoProps` parameter in the new Picker component which is waiting for review here: https://github.com/livechat/design-system/pull/906
