### ISSUE TITLE
[Documentation] Include information about importing styles to target project, update starting project in global README

### ISSUE THREAD

**Issue by marcinsawicki** [livechat/design-system#352]
## Description
We need to update our documentation, and add to README information that in order to use components from DS v1, you need to import styles in your application:
`import '@livechat/design-system-react-components/dist/style.css';`

Also please add information to global README about starting the project. It's not that simple to just run `npm install` and `npm run start`. It's also worth noting that you need to install `volta` and then set proper node version according to our `package.json`

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.20](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.20)
