### ISSUE TITLE
[Documentation] Include rules how to display long strings in components

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#363]
## Description
- Find all elements that might have long strings, that will influence their visual aspect 
- Define in the documentation how they should behave when the string is too long
- Show it in design

**Comment by TomaszRatajczyk** [comment]
1. [Badges](https://613a8e945a5665003a05113b-nhdgxclxti.chromatic.com/?path=/story/components-badge--default) Should accept only two digits number. X>99 should be converted to (+99)

**Comment by sgraczyk** [comment]
@TomaszRatajczyk ☝ 
Applied in https://github.com/orgs/livechat/projects/7/views/1

**Comment by vladko-uxds** [comment]
Show a Tooltip Info when text overflows with an ellipsis [Design Guidelines](https://www.figma.com/file/9FDwjR8lYvincseDkKypC4/Component-Documentations?type=design&node-id=539-32769&mode=design&t=wMRXAKL2RqrmykS9-4)
