### ISSUE TITLE
[Switch] Add loading state, medium size and slightly refresh the UI

### ISSUE THREAD

**Issue by MrVorgoth** [livechat/design-system#371]
Refactor of switch component:
- adding `loading` state,
- adding `medium` size,
- visual refresh of component

Design: https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=1881%3A156

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.19](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.19)
