### ISSUE TITLE
[Button] Adjust spacing for large size

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#378]
**Changes**

- make spacing in all large buttons compatible with our spacings based on 4px grid

**Comment by martagranisz** [comment]
@livechat/design-system what about subtle/float and dotted  buttons? Can't find them in storybook

**Comment by sgraczyk** [comment]
Buttons were probably implemented as-is without proper validation if it covers all design scenarios. I think we should list the differences and implement what's missing.

**Comment by marcinsawicki** [comment]
Will be handled in #548
