### ISSUE TITLE
[Switch] Lock icon invisible in dark theme

### ISSUE THREAD

**Issue by MrVorgoth** [livechat/design-system#380]
## Describe the bug
There is no `lock` icon inside Switch component, when `disabled` prop is passed and dark theme is applied

## Steps to reproduce
1. Go to Switch component on Storybook
2. Click on `Change the theme on the preview` (in case it's hard to find - it's the 4th icon at the top in the middle column)
3. Choose `dark`
4. Scroll down to Stories - States
5. See the disabled state -> no icon is visible

## Expected behavior
Lock icon should be visible (either icon color needs to be changed or the switch color). Right now the switch has forced white design token, that's why it's failing on the dark theme, because on dark theme the icon is also white so white icon on white background is not visible

## Screenshots
How it looks on the white theme:
<img width="128" alt="Screenshot 2022-08-04 at 14 11 43" src="https://user-images.githubusercontent.com/20707838/182846522-755814e3-240e-4ef8-af11-8f388a4f734d.png">

How it looks on dark theme (bug):
<img width="125" alt="Screenshot 2022-08-04 at 14 11 58" src="https://user-images.githubusercontent.com/20707838/182846556-29c1bc57-9141-44c6-a01e-8afc610f8334.png">

## Environment
It doesn't matter - everywhere it'll be the same as it's about wrong design tokens

## Additional context
None

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.22](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.22)
