### ISSUE TITLE
[Switch] Add disabled state without a lock

### ISSUE THREAD

**Issue by MrVorgoth** [livechat/design-system#386]
## Description
Right now when disabled state is turned on a lock icon also appears inside switch. We'd like to have disabled state and disabled state with lock icon.

I propose to have 2 different props for that:
- disabled -> only applies some blur and cursor `not-allowed`
- lock -> applies lock icon in switch
- OTHER alternative could be: `disabled` and `disabledWithLock`

So to get only disabled state we'd need `disabled: true`
And to get disabled state WITH lock icon we'd need: `disabled: true` and `lock: true`

## Design
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=1881%3A156

**Comment by sgraczyk** [comment]
Released in [v1.0.0-alpha.20](https://github.com/livechat/design-system/releases/tag/v1.0.0-alpha.20)
