### ISSUE TITLE
[FormField] Improvements

### ISSUE THREAD

**Issue by kstvsko** [livechat/design-system#392]
## Description

- `FormField` should become a part of the `Input` component, to create a clearer naming,
- The default icon on the left and right should be `emoji` (so it does not create confusion)
- Icons in a `disabled` state should have the Content Basic/Disabled applied,
- `FormField` value named `description` should be renamed to `helperText`, also the name of the component should from now on include `Helper text`, not `Description`.

## Design

**[Figma](https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=4046%3A33393)**

**Comment by VadymBezpalko** [comment]
Currently, it's not possible to merge these two components because it would cause a significant number of changes in existing products that use these components. The issue with the icon styles has been fixed.
