### ISSUE TITLE
[Switch] Change padding

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#393]
## Steps to reproduce
1. Go to 'Storybook'
2. Click on 'Switch/ sizes'
3. Scroll down to 'medium/large'
4. Check the padding of the circle in component > 3px

## Expected behavior
Smaller side padding should be like on the design : 2px;

## Screenshots
![image](https://user-images.githubusercontent.com/46165804/185190213-7938ecc2-62bd-425a-92a7-2e54962786fb.png)

## Environment
Storybook

**Comment by marcinsawicki** [comment]
Already solved
