### ISSUE TITLE
[Tag] Improvements

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#405]
## Description
- change the color of the default tag/ filter
- missing small size (height: 20px;)
- missing filter behavior

## Design
TBA
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=3471%3A19134

**Comment by martagranisz** [comment]
✋ I have some doubts about: 

- Should we really unify tags and filters? Should they look the same if the usage and behavior of the components are different? 
- Should tags and filters be so sterile? (grey) As for the tags that users assign to chats I can imagine that they should be visible at the first glance. Both for the user who is assigning tags to the chats, as well as for the admin who is entering a particular chat/ archive/ ticket.

**Comment by marcinsawicki** [comment]
Already solved
