### ISSUE TITLE
[Promo banner] Wrong paddings 

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#407]
BUG #1
## Describe the bug
- padding between the buttons is too big (follow the design)

## Steps to reproduce 
1. Go to 'Storybook'
2. Click on 'Promo banner'3
3. See that there is padding between buttons (24+16px)

## Expected behavior
Padding should be equal 16px; 

## Screenshots
<img width="417" alt="image" src="https://user-images.githubusercontent.com/46165804/188313537-92fe882e-74f2-47a5-9543-e4aec1ffc85a.png">

BUG #2

## Describe the bug
- wrong side buttons margins

## Steps to reproduce 
1. Go to 'Storybook'
2. Click on 'Promo banner'3
3. See 56px button left-padding, and 56px+16px+20 =94px

## Expected behavior
left-padding: 76px;
right-padding: 92px;

## Screenshots
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/46165804/188313698-4594c589-5b7b-439b-9539-134179254abb.png">

**Comment by marcinsawicki** [comment]
Already solved
