### ISSUE TITLE
[PromoBanner] Lacking possibility to set buttons vertically

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#408]
## Describe the bug
There is no option to set buttons vertically

## Steps to reproduce 
1. Go to 'Storybook'
2. Click on 'Promo banner'
3. Go to the smallest version of the banner
4. See that there is no way to set buttons vertically

## Expected behavior
There should be an option where the user sets buttons one beneath another

## Screenshots
<img width="280" alt="image" src="https://user-images.githubusercontent.com/46165804/188314546-33b6790e-a8d9-4104-a6db-5e00aeff6525.png">

**Comment by sgraczyk** [comment]
@martagranisz Am I correct to assume that you expect us to introduce a `prop` to control button orientation `vertical | horizontal`? I'm not convinced as it will work only when a specific breakpoint will hit. 

Shouldn't we actually enforce `vertical` alignment in case of that `small` variant? (via media queries).
