### ISSUE TITLE
[FormField] Improvements

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#410]
## Description

- once input is in error state, the error message should replace the description 
- add a new variant of an error input with error message displayed on the tooltip 

## Design
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=4211%3A42610

**Comment by marcinsawicki** [comment]
Need to verify after components audit.

**Comment by marcinsawicki** [comment]
In this iteration, we will not add the possibility to show error message in the tooltip.
