### ISSUE TITLE
[Button] Add outline variant to the Destructive type of button

### ISSUE THREAD

**Issue by kstvsko** [livechat/design-system#434]
## Description
Add outline variant to the Destructive type of button for all the states:
- Enabled
- Hover
- Disabled
- Active
- Loading

## Design
<img width="724" alt="image" src="https://user-images.githubusercontent.com/109948903/192241970-6b0eba21-ad3b-44a4-8365-ffe6c73b9c64.png">

[**Figma**](https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=1534%3A35)

**Comment by marcinsawicki** [comment]
Need to verify with @kstvsko

**Comment by VadymBezpalko** [comment]
It's done. 
<img width="494" alt="image" src="https://github.com/livechat/design-system/assets/12149393/1af9bbf7-325a-4ca0-96a2-c01d3af62de7">
