### ISSUE TITLE
[SearchInput] Problem with size property

### ISSUE THREAD

**Issue by JoannaSikora** [livechat/design-system#436]
## Description
There is a problem with setting "size" property
<img width="817" alt="Screenshot 2022-09-27 at 09 56 04" src="https://user-images.githubusercontent.com/37884374/192467998-c58e3935-4521-4ec3-9495-6bd79fe70101.png">
<img width="977" alt="Screenshot 2022-09-27 at 09 54 34" src="https://user-images.githubusercontent.com/37884374/192468031-d9a39d61-e4c8-40f1-94bc-ee94155706a6.png">
<img width="1241" alt="Screenshot 2022-09-27 at 09 54 20" src="https://user-images.githubusercontent.com/37884374/192468047-4b36d53b-a04b-4bbf-a2f8-683f340aad99.png">

**Comment by marcinsawicki** [comment]
Already solved
