### ISSUE TITLE
[Tooltip] Fix placement bottom-end

### ISSUE THREAD

**Issue by JoannaSikora** [livechat/design-system#438]
## Description
Arrow is too far right when using placement bottom-end
<img width="397" alt="Screenshot 2022-09-27 at 10 08 20" src="https://user-images.githubusercontent.com/37884374/192470643-8720f3bb-47c0-4939-9344-5472fe05226b.png">

**Comment by VadymBezpalko** [comment]
After implementing Floating-UI lib it works as expected: 
<img width="264" alt="image" src="https://github.com/livechat/design-system/assets/12149393/a944d5cc-7e14-480f-92a2-081b7bd71561">
