### ISSUE TITLE
[Modal buttons] Set buttons length to even

### ISSUE THREAD

**Issue by martynabargiel** [livechat/design-system#446]
## Description
In centered-button groups (where there’s the primary and secondary/tertiary next to each other) we’re now using different button lengths (they scale to the provided text label). The buttons should be even and that probably requires the modal to scale bigger to accommodate now longer buttons (the shorter will take the longer's length).  The modals would need to embrace some rules regarding the paddings then.

The problem applies to:
1) alert/confirmation modals with the centered button groups
2) save bar in the Team section (also with the centered button groups)

Slack thread: https://livechat.slack.com/archives/CA945NPQR/p1665066674959469

<img width="765" alt="Zrzut ekranu 2022-10-6 o 16 30 58 (1)" src="https://user-images.githubusercontent.com/74004180/197263229-f77d3e65-7ab1-4028-859f-c584734c23a3.png">

![Group Created](https://user-images.githubusercontent.com/74004180/197821414-2dd7803b-464f-463d-9ebf-52a57d87d868.png)
![Confirm](https://user-images.githubusercontent.com/74004180/197821436-66a7296d-2e0d-41c0-9a58-f28ce46d9e30.png)

**Comment by marcinsawicki** [comment]
Already solved
