### ISSUE TITLE
[Design color tokens] Modify design tokens

### ISSUE THREAD

**Issue by martagranisz** [livechat/design-system#478]
1. add **$surface-basic-default-hover** token  
legacy: #F3F6F7
light: #EFEFF0
dark: rgba(255, 255, 255, 0.1)

2. add **$surface-basic-default-active**  token
legacy: #EBF1F4
light: #E5E5E6
dark: rgba(255, 255, 255, 0.2)

3. add **$surface-basic-default-disabled** token
legacy: #F9FAFB
light: #F6F6F7
dark: #333338

4. change name: $surface-basic-hover to $surface-basic-subtle-hover
5. change name: $surface-basic-active to $surface-basic-subtle-active
6. change name: $surface-basic-disabled to $surface-basic-subtle-disabled

7. In light palete  change color of **surface-basic-subtle-hover** to - #D2D2D5

https://www.figma.com/file/lfffziWFstJuHP0CNJ1QK6/Playground?node-id=135%3A27672&t=4rqde5hZaIyt8j3p-1

**Comment by marcinsawicki** [comment]
Already done
