### ISSUE TITLE
Popover - run optional custom handler on document click.

### ISSUE THREAD

**Issue by MateuszRomek** [livechat/design-system#490]
## Description
Popover should accept the optional handler `onClose/onDocumentClick`, which should be run on `document click`. 
I think it could be handled here https://github.com/livechat/design-system/blob/v1/packages/react-components/src/components/Popover/Popover.tsx#L66-L72

Use case: 
I need to change state in the custom component when the user clicks outside popover 

## Design
n/a

**Comment by VadymBezpalko** [comment]
Will be fixed in https://github.com/livechat/design-system/pull/875
