### ISSUE TITLE
[Popover] Add 'display' style as inline style

### ISSUE THREAD

**Issue by bbcz** [livechat/design-system#523]
_**Popover + jest**_

We using RTL for testing witch operates only on the rendered fragment of the code - so not all css classes are loaded. In the case of Popover, we are unable to verify that the user is actually seeing the content of Popover with RTL - all content is always visible in DOM - so we can’t use assertion `.tobeVisible()` 

**q1:** are you covering the case of a "visible" in the tests on your side ? 
**q2**: can we add display as inline style ? or some better solution for this case

_example_
   ```
await act(async () => {
      await user.click(menuButton);
    });

    for (const item of dataItems) {
      const itemdropdown = await screen.findByText(item.content);
      expect(itemdropdown).toBeVisible();
    }
```

_it pass - even if we skip act_

_note:_ the same problem is in https://github.com/livechat/design-system/blob/01d4f5db9a8c80bc7acb3117a4d3991430803ec5/packages/react-components/src/components/Popover/Popover.spec.tsx#L52

**Comment by VadymBezpalko** [comment]
This issue will be resolved with https://github.com/livechat/design-system/pull/875 - after these changes the content will be synchronized with what the user is seeing and content will be normally removed from DOM
