### ISSUE TITLE
[Button] Create Floating Button

### ISSUE THREAD

**Issue by rafalluksza** [livechat/design-system#543]
## Description
Introduce new kind for button => Floating
## Design
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=3403-21864&t=u2jtGmV5B8mFrrVj-0

**Comment by ThienBNguyen** [comment]
Hi rafalluksza, 
I am really interested in this issue. Can I work on it? thanks
