### ISSUE TITLE
[Tag Input] & [Email Tag Input] - fixes

### ISSUE THREAD

**Issue by marcinsawicki** [livechat/design-system#552]
## Description
Spacing should be set to 6px

## Design
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=3484-19051&t=nj3kPivwZOmLrwKq-4

**Comment by vladko-uxds** [comment]
Correct link https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=6231-34346&t=aD6w3mmgAr6qOIj7-4
