### ISSUE TITLE
[Multiple picker] - Border radius

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#684]
Please update border radius for **Multiple picker** component
https://v1--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-picker--default

Field border-radius:
`--spacings-border-radius-md`

Picker Tag border-radius:
`--spacings-border-radius-xs`

Design spec
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=6122-61558&mode=dev

**Comment by marcinsawicki** [comment]
It will be changed in #685
