### ISSUE TITLE
[Avatar] - New size variant and naming(breaking changes)

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#696]
Please add 
- Avatar 40x40px , size name: " Large"

Note: Other "Larger" avatars should change their names accordingly
- Large(48px) -> XLarge
- XLarge (64px) -> 2XLarge
- 2XLarge (96px) -> 3XLarge

See design 
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=736-8527&mode=design&t=rE9GHkMx29a6CsOG-4

**Comment by marcinsawicki** [comment]
Blocked until we release the new version with fixes, because here we implement the breaking changes that may cause problems in currently implemented components
