### ISSUE TITLE
[PromoBanner ] - Radius token

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#714]
Apply radius token `--radius-3 ` to current Promo banner

![Image](https://user-images.githubusercontent.com/125188605/257483571-d8fbc6a6-68c1-4698-8d9c-4fd873f8de2a.png)

https://refresh-ui--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-promobanner--promo-banner

**Comment by marcinsawicki** [comment]
Relates to: #709
