### ISSUE TITLE
[Modal] - Bug with Header position

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#720]
**Actual results**
- the modal title is moved to the next line
- close icon moved to the next line

![Image](https://user-images.githubusercontent.com/125188605/258452503-0e952f3c-b7a2-46b2-b802-d3bdf1f779cf.png)

https://refresh-ui--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-modal--modal-with-labeled-header

https://refresh-ui--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-modal--modal-with-custom-header

**Expected results:**
Modal title in one line with Left icon and close icon

![Image](https://user-images.githubusercontent.com/125188605/258453464-16a57597-ada1-4e2a-933b-ee47c553eaee.png)

**Comment by marcinsawicki** [comment]
Already solved
