### ISSUE TITLE
When Switch is ON as initial state, it always has "checked" attribute"

### ISSUE THREAD

**Issue by shwarcu** [livechat/design-system#721]
## Describe the bug

`checked` attribute is not removed when switch is toggled off. Despite visuals are okay and events are called correctly, switch is recognised by React Testing Library as "checked" despite it's state.

## Steps to reproduce

1. Go to https://design.livechat.com/?path=/story/components-switch--states
2. inspect first switch that is enabled and check it's attributes
3. Click switch on and off
4. `checked` is always present

## Expected behavior

`checked` should be removed when switch is in OFF state.

## Screenshots

https://github.com/livechat/design-system/assets/58426925/78618b73-8c63-47d1-a198-af5cef967626

## Environment

- Design system package(s) version: @livechat/design-system-react-components@^1.0.0-alpha.60

## Additional context

Caught when writing component test in RTL.
When clicked switch changes visually and it triggers events, however `checked` attribute causes tests to fail

```ts
    const mySwitch = rtl.getByTestId('my-switch-id');
    await userEvent.click(mySwitch);

    expect(statusSwitch).not.toBeChecked(); // fails
```

**Comment by VadymBezpalko** [comment]
Hello, @shwarcu. I've observed some strange behavior related to the checked attribute in Chrome DevTools. It always displays the checked attribute, despite its internal state being properly changed. Additionally, the dev console shows the correct value for the checked parameter. Here is proof:: https://monosnap.com/file/QU8vxNfBpi9Bd1QAuSiAYtUjKJm0O9
