### ISSUE TITLE
[Button] - Rename Subtle button to Plain button

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#724]
In storybook
![Image](https://user-images.githubusercontent.com/125188605/259662183-1929ce03-59a0-4028-98c3-ecd106fdbc8b.png)

Design spec
https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?type=design&node-id=1534-201&mode=design&t=WRXWs6Vx70wRgrKs-4

**Comment by marcinsawicki** [comment]
Relates to: #723
