### ISSUE TITLE
[Tooltip] - Interactive tooltip types

### ISSUE THREAD

**Issue by MrVorgoth** [livechat/design-system#817]
### Description

I wanted to use icon inside `primaryButton` prop inside `Interactive` tooltip component, however I stumbled upon such props: `handleClick` / `label` / `kind (optional)`. I thought I will be able to just use any other `Button` component inside `primaryButton` prop, but I couldn't do it. Can you type that any `ReactNode` can go there?

Also I wonder why it was designed to have `<Interactive />` component placed inside `<Tooltip />` component. As a developer I thought I would use it the same way I use normal tooltip: `<InteractiveTooltip (all props from normal tooltip + props from interactive tooltip />`. Can you think about such implementation?

UPDATE: Please also export a `TooltipButton` type.

**Comment by vladko-uxds** [comment]
Improve storybook doc : how to use formfield +input
