### ISSUE TITLE
Keyboard control in components

### ISSUE THREAD

**Issue by marcinsawicki** [livechat/design-system#819]
We should analyze the current implementation of keyboard control of a component. In some cases, e.g.`Picker`, after opening the list, we listen for specific events and block their execution for control purposes. This solution may block other keyboard events in a given environment. We should analyze whether it is possible to close keyboard support strictly in a given component, and whether event listeners are added and removed correctly.

**Comment by vladko-uxds** [comment]
Include keyboard control interaction for new components
