### ISSUE TITLE
[Button] - Update button height

### ISSUE THREAD

**Issue by vladko-uxds** [livechat/design-system#920]
Button should have instead of fixed `height`->`min-height` and specific `padding(top-bottom)`

- [ ] Primary
- [ ] Secondary
- [ ] Destructive
- [ ] Float button
- [ ] Plain button
- [ ] HighContrast

Compact size:
`min-height: 32px`
`padding -top/bottom: 6px`

Medium size:
`min-height: 36px`
`padding -top/bottom: var(--spacing-2)`

Large size:
`min-height: 44px`
`padding -top/bottom: var(--spacing-3)`

**Comment by VadymBezpalko** [comment]
Unfortunately, implementing these changes will lead to a breaking change, as altering the `height` parameter to `min-height` could disrupt the visual appearance in scenarios where a custom `height` is used, both within and outside DS components. Setting a `min-height` value could override any custom `height` that is set to be less than the proposed `min-height`.
To avoid causing visual issues in existing implementations, it is better to introduce this improvement in the next `major` version of the library.
