### ISSUE TITLE
[BUG] VisibilityOn icon "currentColor" fill

### ISSUE THREAD

**Issue by JankaTee** [livechat/design-system#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the VisibilityOn icon we have noticed the css class has assigned “currentColor” to the fill property which results in the entire icon being filled with its border color and making it look a bit like a dumpling. When we overwrite the “currentColor” with “none” all is good, but should we overwrite it or is this something you can address on your side?
![image (44)](https://github.com/livechat/design-system/assets/107029278/45018dc6-5563-4b25-9031-ae2c0b524077)
![image (43)](https://github.com/livechat/design-system/assets/107029278/046f2cca-06ef-4b7e-92ba-e66b0b553ee7)
![image (42)](https://github.com/livechat/design-system/assets/107029278/c9210044-0e71-4f4f-8744-66b6e898b037)

### Steps To Reproduce

1. Go to Console: https://platform.text.com/console/apps/your
2. Choose one of the apps or create a new one 
3. In the side menu choose "Variables" 
![image (45)](https://github.com/livechat/design-system/assets/107029278/80578cc2-ceef-4fc0-afa5-26209c14867a)

### Expected Behavior

For the icon not to fill by default since we have a separate filled icon available (VisibilityOnFilled). 

### Design system package(s) version

@livechat/design-system-icons”: “^1.6.1”

**Comment by JankaTee** [comment]
Also same thing happens for "OpenInNew" icon. And side note: we are only using the Dark Theme, I don't know if that matters.

**Comment by VadymBezpalko** [comment]
Closing the issue, because icons were used with old library, not the new one.
Slack: https://text.slack.com/archives/CA945NPQR/p1706800263116459?thread_ts=1706182599.339599&cid=CA945NPQR
